name: CI for Playwright and Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  orange_hrm_playwright:
    name: Playwright Tests for orange_hrm_playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies in orange_hrm_playwright
        run: npm install
        working-directory: orange_hrm_playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: orange_hrm_playwright

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: orange_hrm_playwright

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: orange_hrm_playwright/playwright-report/

  loop_qa_playwright:
    name: Playwright Tests for loop_qa_playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies in loop_qa_playwright
        run: npm install
        working-directory: loop_qa_playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: loop_qa_playwright

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: loop_qa_playwright

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-loop_qa
          path: loop_qa_playwright/playwright-report/

  delek_homes_cypress:
    name: Cypress Tests for delek_homes_cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies in delek_homes_cypress
        run: npm install
        working-directory: delek_homes_cypress

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: delek_homes_cypress

      - name: Upload Cypress report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: delek_homes_cypress/cypress/report/
